[package]
name = "naumachia"
description = "Cardano Smart-Contract Framework"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Mitchell Turner"]
license = "Apache-2.0"
repository = "https://github.com/MitchTurner/naumachia"

[workspace]
members = [
    "sample-dApps/*",
    "trireme"
]

[dependencies]
serde = { version = "1.0.143", features = ["derive"] }
serde_with = {version = "2.0.0", features = ["json"]}
serde_json = "1.0"
thiserror = "1.0.24"
tokio = { version = "1.20.1", features = ["full"] }
reqwest = { version = "0.11.11", features = ["json"] }
url = "2.2.2"
toml = "0.5.9"
cardano-multiplatform-lib = "3.1.1"
tiny-bip39 = "1.0.0"
futures = "0.3.23"
async-trait = "0.1.57"
hex = "0.4.3"
blockfrost-http-client = "0.0.8"
dirs = "4.0.0"
uplc = { git = "https://github.com/txpipe/aiken.git", branch = "main"}
tempfile = "3.3.0"
minicbor = "0.18.0"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[dev-dependencies]
clap = { version = "3.2.16", features = ["derive"] }
proptest = "1.0.0"
rand = "0.8.5"
sha2 = "0.10.6"

[patch.crates-io]
blockfrost-http-client = { path = "../blockfrost-http-client", version = "0.0.8"}
cardano-multiplatform-lib = { path = "../forks/cardano-multiplatform-lib/rust", version = "3.1.1"}