[package]
name = "naumachia"
description = "PAB but Rusty"
version = "0.0.1"
edition = "2021"
authors = ["Mitchell Turner"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = {version = "2.0.0", features = ["json"]}
serde_json = "1.0"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[dev-dependencies]
clap = { version = "3.2.16", features = ["derive"] }
proptest = "1.0.0"
rand = "0.8.5"
tempfile = "3.3.0"
